# Generated by Django 5.2.6 on 2025-09-27 01:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Criterio de clasificación',
                'verbose_name_plural': 'Criterios de clasificación',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_name', models.CharField(help_text='Nombre descriptivo de la fuente del extracto (p.ej. banco o cuenta).', max_length=255)),
                ('file_name', models.CharField(help_text='Nombre del fichero CSV importado para trazabilidad.', max_length=255)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en la que se procesó el fichero.')),
            ],
            options={
                'verbose_name': 'Importación de extracto',
                'verbose_name_plural': 'Importaciones de extractos',
                'ordering': ('-imported_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ClassificationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='invoice_classifier.classificationcriterion')),
                ('parent', models.ForeignKey(blank=True, help_text='Permite crear jerarquías de etiquetas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='invoice_classifier.classificationlabel')),
            ],
            options={
                'verbose_name': 'Etiqueta de clasificación',
                'verbose_name_plural': 'Etiquetas de clasificación',
                'ordering': ('criterion', 'name'),
                'unique_together': {('criterion', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=255)),
                ('normalized_concept', models.CharField(blank=True, help_text='Concepto estandarizado para facilitar búsquedas y reglas.', max_length=255)),
                ('booking_date', models.DateField(help_text='Fecha del movimiento en el extracto.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importe del movimiento. Valores negativos indican cargos.', max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, help_text='Saldo disponible tras aplicar el movimiento.', max_digits=12)),
                ('currency', models.CharField(default='EUR', help_text='Divisa del movimiento siguiendo el código ISO 4217.', max_length=3)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Datos originales adicionales del CSV para auditoría.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.ForeignKey(help_text='Importación a la que pertenece el movimiento.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invoice_classifier.statementimport')),
            ],
            options={
                'verbose_name': 'Movimiento bancario',
                'verbose_name_plural': 'Movimientos bancarios',
                'ordering': ('-booking_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TransactionClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('automatic', 'Automática'), ('manual', 'Manual'), ('imported', 'Importada')], default='automatic', help_text='Origen de la clasificación para auditoría y backtrace.', max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, default=1, help_text='Confianza (0-1) de la clasificación automática.', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='invoice_classifier.classificationlabel')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='invoice_classifier.banktransaction')),
            ],
            options={
                'verbose_name': 'Clasificación de movimiento',
                'verbose_name_plural': 'Clasificaciones de movimientos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['booking_date', 'concept'], name='invoice_cla_booking_f28585_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['normalized_concept'], name='invoice_cla_normali_de7725_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionclassification',
            unique_together={('transaction', 'label', 'source')},
        ),
    ]
