# Generated by hand for adding the original_file field

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_classifier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementimport",
            name="original_file",
            field=models.FileField(
                help_text="Archivo CSV original subido por el usuario.",
                null=True,
                upload_to="statements/",
            ),
        ),
    ]
